# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: eddiewebb/bitbucket-pipelines-marketplace:latest

pipelines:
  default:
    - step:
        script:
          - bash shipit.sh
