[@ww.textfield labelKey="scp.task.host" name="host" required='true'/]
[@ww.textfield labelKey="scp.task.port" name="port" required='false'/]
[@ww.textfield labelKey="scp.task.username" name="username" required='true'/]

[@ww.select labelKey='scp.task.authentication' name='authType' required="true" list=authenticationTypes listKey='key' listValue='displayName' toggle=true /]

[@ui.bambooSection dependsOn='authType' showOn='PASSWORD']
    [#if context.get("password")?has_content]
        [@ww.checkbox labelKey='scp.task.password.change' toggle=true name='change_password' /]
        [@ui.bambooSection dependsOn='change_password' showOn=true]
            [@ww.password labelKey='scp.task.password' name='password' required='true' /]
        [/@ui.bambooSection]
    [#else]
        [@ww.hidden name='change_password' value=true /]
        [@ww.password labelKey='scp.task.password' name='password' required='true' /]
    [/#if]
[/@ui.bambooSection]

[@ui.bambooSection dependsOn='authType' showOn='KEY KEY_WITH_PASSPHRASE']
    [#if context.get('private_key_defined')?has_content]
        [@ww.checkbox labelKey='scp.task.key.change' toggle='true' name='change_key'/]
        [@ui.bambooSection dependsOn='change_key' showOn=true]
            [@ww.file labelKey='scp.task.key' name='private_key' required="true" /]
        [/@ui.bambooSection]
    [#else]
        [@ww.hidden name='change_key' value=true /]
        [@ww.file labelKey='scp.task.key' name='private_key' required="true" /]
    [/#if]
[/@ui.bambooSection]

[@ui.bambooSection dependsOn='authType' showOn='KEY_WITH_PASSPHRASE']
    [#if context.get('passphrase')?has_content]
        [@ww.checkbox labelKey='scp.task.passphrase.change' toggle=true name='change_passphrase' /]
        [@ui.bambooSection dependsOn='change_passphrase' showOn=true]
            [@ww.password labelKey='scp.task.passphrase' name='passphrase' required='true' /]
        [/@ui.bambooSection]
    [#else]
        [@ww.hidden name='change_passphrase' value=true /]
        [@ww.password labelKey='scp.task.passphrase' name='passphrase' required='true' /]
    [/#if]
[/@ui.bambooSection]

[@ww.textfield labelKey="reversescp.task.remote.path" name="remotePath" required='true'/]
[@ww.textfield labelKey="reversescp.task.remote.pattern" name="remotePattern"/]
[@ww.textfield labelKey="reversescp.task.local.path" name="localPath" required='true'/]