[@ww.textfield labelKey="Host" name="host" required='true'/]
[@ww.textfield labelKey="Username" name="username" required='true'/]

[#if mode == "create"]
    [@ww.password labelKey="Password" name="password" required='true'/]
	[@ww.textarea labelKey="Inline Script" name="inlineScript" required='true'/]
[#elseif mode == "edit"]
    [@ww.checkbox labelKey="Change Command or Password?" toggle='true' name='change_command'/]
    [@ui.bambooSection dependsOn='change_command' ]
    [@ww.password labelKey="New Password" name="new_password" required='true'/]
    [@ww.textarea labelKey="New Inline Script" name="inlineScript" required='true'/]
    [/@ui.bambooSection]
[/#if]

[@ww.textfield labelKey="Timeout" name="timeout" required='true'/]